# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trix < Formula
  desc "Trix CLI - A universal memory layer for AI agents and humans"
  homepage "https://trixdb.com"
  version "0.4.7"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trixdb/trix/releases/download/v0.4.7/trix_0.4.7_darwin_x86_64.tar.gz"
      sha256 "6d8ff328c30eec35cf5fe81a7aa4a06a0e49edf41e23e8debe9f19c245a6414e"

      def install
        bin.install "trix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trixdb/trix/releases/download/v0.4.7/trix_0.4.7_darwin_arm64.tar.gz"
      sha256 "6a05e7ffdb2d44fe01626503f2297ae54a11c2c0640a406fffe5d1372617df12"

      def install
        bin.install "trix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trixdb/trix/releases/download/v0.4.7/trix_0.4.7_linux_x86_64.tar.gz"
      sha256 "e9e27ec304056fea30e393cff512970812ad1434078d075910c261ffc89c3df4"
      def install
        bin.install "trix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trixdb/trix/releases/download/v0.4.7/trix_0.4.7_linux_arm64.tar.gz"
      sha256 "8ec55bf2d04d9e8037ef8a928a3b734447e0a027eb45518a77b36f2502b2a6c1"
      def install
        bin.install "trix"
      end
    end
  end

  test do
    system "#{bin}/trix", "--version"
  end
end
